#!/bin/bash

echo ""
echo "Please download you chosen binary from the 'Artifacts' section of the latest run in the 
'Actions' tab of the repo!"
echo "Then ensure that the binary has been moved to the git cloned directory and is named 'gcheat_binary'!"
echo ""
location=$(pwd)
chmod +x gcheat_binary
cat << EOF >> gcheat
#!/bin/bash
${location}/gcheat_binary ${location}/README.md
EOF

read -p "Enter your filepath to store command e.g. [/usr/local/bin]': " store_cmd_location

mv gcheat ${store_cmd_location}/gcheat
chmod +x ${store_cmd_location}/gcheat

if [[ $? == 0 ]] ; then
    echo "Success!! Use the command \`gcheat\` to use."
    exit 0
else
    echo "Error!! If you can't figure it out please report an issue!"
    exit 1
fi
